### ISSUE TITLE
__chkstk not currently emitted.

### ISSUE THREAD

**Issue by ZacWalk** [Windows-on-ARM-Experiments/mingw-woarm64-build#12]
Large stack allocations on WIndows should emit __chkstk.

**Comment by eukarpov** [comment]
Issue is related to stack probing and has been fixed by this PR
[Enable stack probing on Aarch64 mingw to prevent crash on stack growth](https://github.com/Windows-on-ARM-Experiments/gcc-woarm64/pull/11)
