### ISSUE TITLE
GCC: -mms-bitfields is unsupported

### ISSUE THREAD

**Issue by carlo-bramini** [Windows-on-ARM-Experiments/mingw-woarm64-build#196]
I tried to build GLIB-2.80.5 and, after configuring with `meson`, I run `ninja` for building.
Unfortunately, the process stopped immediately with this message:
```
aarch64-w64-mingw32-gcc: error: unrecognized command-line option '-mms-bitfields'
ninja: build stopped: subcommand failed.
```
Is it correct that `aarch64-w64-mingw32-gcc` doesn't support this option?

**Comment by Blackhex** [comment]
Hello Carlo. Thank you for reporting this issue. We need to investigate whether the `aarch64-w64-mingw32` target GCC should support this option.
